
server:
  port: 9887

security:
  signing-key: UgxH7iuGS3yqwLx #https://www.random.org/strings/
  security-realm: Sample Default Realm
  jwt:
    local-resource-id: localjwtresourceid



spring:

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    database: default
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:15432/postgres
      username: postgres
      password: rootroot

      initial-size: 1
      max-active: 10
      max-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      max-wait: 10000
      min-evictable-idle-time-millis: 30000
      log-abandoned: true
      test-while-idle: true
      validation-interval: 300000
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=10000)


