
server:
  port: 9880


spring:
  security:
    oauth2:
      client:
        registration:
          custom-client:
            provider: custom-provider
            client-id: default_oauth2_client_id
            client-secret: QWERTY74gray75raccoon634
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: read
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Login Client
        provider:
          custom-provider:
            authorization-uri: http://localhost:9887/oauth/authorize
            token-uri: http://localhost:9887/oauth/token
            user-info-uri: http://localhost:9887/ws/authenticated/getMe
            user-name-attribute: username
